=== ManuelSolar/ManuelSolar.github.io/tema7/alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="ciclo" type="tipoCiclo"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="tipoCiclo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DAW"/>
      <xs:enumeration value="ASIR"/>
      <xs:enumeration value="Cocina"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ManuelSolar/ManuelSolar.github.io/tema7/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="alumnos.xsd">
    <alumno>
      <nombre>David</nombre>
      <ciclo>DAW</ciclo>
    </alumno>
    <alumno>
      <nombre>Antonio</nombre>
      <ciclo>ASIR</ciclo>
    </alumno>
    <alumno>
      <nombre>Rafa</nombre>
      <ciclo>Cocina</ciclo>
    </alumno>
</alumnos>
